GOOSE_CLI_THEME: dark
GOOSE_PROVIDER: anthropic
extensions:
  computer-controller:
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  knowledge-graph-memory:
    args:
    - run
    - npm:@modelcontextprotocol/server-memory
    cmd: deno
    enabled: true
    envs: {}
    name: knowledge-graph-memory
    timeout: 300
    type: stdio
  memory:
    enabled: true
    name: memory
    timeout: 300
    type: builtin
  sequential-thinking:
    args:
    - run
    - --allow-env
    - npm:@modelcontextprotocol/server-sequential-thinking
    cmd: deno
    enabled: true
    envs: {}
    name: sequential-thinking
    timeout: 300
    type: stdio
OPENAI_HOST: https://api.openai.com
GOOSE_MODEL: claude-sonnet-4-20250514
OPENAI_BASE_PATH: v1/chat/completions
GOOSE_MODE: auto
