[tools]
bun = "latest"
deno = "latest"
go = "latest"
herdr = "latest"
node = "latest"
"npm:@antfu/ni" = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
