hl.on("hyprland.start", function()
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("vicinae server")
	hl.exec_cmd("steam -silent")
	hl.exec_cmd("asm-gui --systray")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'")
	hl.exec_cmd("xrandr --output DP-2 --primary")
	-- hl.exec_cmd("easyeffects --service-mode")
end)
