# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,24

# Dark mode
exec = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = GTK_USE_PORTAL,1

xwayland {
  force_zero_scaling = true
}

# Don't show update on first launch
ecosystem {
  no_update_news = true
}

# Gaming stuff
env = PROTON_FSR4_UPGRADE,1
env = PROTON_FSR4_RDNA3_UPGRADE,1
env = PROTON_XESS_UPGRADE,1
env = PROTON_NO_WM_DECORATION,1
# env = PROTON_ENABLE_WAYLAND,1 # Experimental, may use only if needed
env = PROTON_USE_NTSYNC,1 # Experimental
env = RADV_PERFTEST,aco
env = MESA_GLTHREAD,true
env = ENABLE_LAYER_MESA_ANTI_LAG,true
env = MANGOHUD,1
env = LSFG_DLL_PATH="/mnt/games/SteamLibrary/steamapps/common/Lossless Scaling/Lossless.dll"
